export const COMMON_PRONOUNS = [
  "she/her",
  "he/him",
  "they/them",
  "she/they",
  "he/they",
  "xe/xem",
  "ze/zir",
  "fae/faer",
  "it/its",
  "any/all",
  "ask me",
  "name only",
];

export const COMMON_LANGUAGES = [
  ["en", "English"],
  ["de", "Deutsch"],
  ["fr", "Français"],
  ["es", "Español"],
  ["pt", "Português"],
  ["it", "Italiano"],
  ["nl", "Nederlands"],
  ["pl", "Polski"],
  ["ru", "Русский"],
  ["uk", "Українська"],
  ["cs", "Čeština"],
  ["sv", "Svenska"],
  ["fi", "Suomi"],
  ["ja", "日本語"],
  ["zh", "中文"],
  ["ko", "한국어"],
  ["ar", "العربية"],
  ["tr", "Türkçe"],
  ["id", "Bahasa Indonesia"],
  ["hi", "हिन्दी"],
] as const;
