/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'blue.pronouns.name'

export { $nsid }

type Main = {
  $type: 'blue.pronouns.name'
  value: string
  preferred: boolean

  /**
   * BCP-47 language tag (e.g. 'en', 'de', 'zh-CN'). Omit or default to 'en' for English.
   */
  lang?: string
  sortOrder?: number
  createdAt: l.DatetimeString
  updatedAt: l.DatetimeString
}

export type { Main }

const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    value: l.string({ maxLength: 64, minLength: 1, maxGraphemes: 64 }),
    preferred: l.boolean(),
    lang: l.optional(l.string({ maxLength: 35, minLength: 2 })),
    sortOrder: l.optional(l.integer({ minimum: 0, maximum: 127 })),
    createdAt: l.string({ format: 'datetime' }),
    updatedAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
